[package]
name = "frb_plugin_tool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
duct = "0.13.7"
futures = "0.3.30"
tera = "1.x"
tokio = { version = "1.35.1", features = ["full"] }
